// <auto-generated />
namespace AngularPOC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class N1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(N1));
        
        string IMigrationMetadata.Id
        {
            get { return "201310281216029_N1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
